CREATE DATABASE IF NOT EXISTS myburger;
USE myburger;


CREATE TABLE IF NOT EXISTS myburger.users (
  id INT NOT NULL AUTO_INCREMENT   PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `restaurant` VARCHAR(150) NOT NULL,
  `message` VARCHAR(300) NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS myburger.users2 (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    confirmpassword VARCHAR(255) NOT NULL,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
